---
title: "p8105_hw2_akg2197"
author: "Annie Gorman"
date: "2024-09-29"
output: github_document
---
```{r setup}
library(tidyverse)
```

## Problem 1

## Problem 2

```{r}
library(readxl)
trashwheel_df <- read_excel("~/Downloads/202409 Trash Wheel Collection Data.xlsx", sheet = 1, range = "A2:N653")

trashwheel_df=trashwheel_df |>
  janitor::clean_names()|>
  drop_na(dumpster)

trashwheel_df = trashwheel_df |>
  mutate(sports_balls = as.integer(sports_balls))

library(readxl)
proftrashwheel_df <- read_excel("~/Downloads/202409 Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M121")

proftrashwheel_df=proftrashwheel_df |>
  janitor::clean_names()|>
  drop_na(dumpster)

library(readxl)
gwynnda_df <- read_excel("~/Downloads/202409 Trash Wheel Collection Data.xlsx", sheet = 4, range = "A2:L265")

gwynnda_df=gwynnda_df |>
  janitor::clean_names()|>
  drop_na(dumpster)

dplyr:::left_join.data.frame(trashwheel_df, proftrashwheel_df, gwynnda_df, by = "volume_cubic_yards")
```
## Problem 3 
```{r}
bakers = read_csv ("~/Desktop/p8105_hw2_akg2197/gbb_datasets 2/bakers.csv", na =c("", "N/A", "Unknown", "UNKNOWN")) |>
  janitor::clean_names()
bakes = read_csv ("~/Desktop/p8105_hw2_akg2197/gbb_datasets 2/bakes.csv") |>
 janitor::clean_names()
results = read_csv("~/Desktop/p8105_hw2_akg2197/gbb_datasets 2/results.csv", skip = 2), c("", "N/A", "Unknown", "UNKNOWN")) |>
 janitor::clean_names()
 
bakers=
  bakers |> rename(baker = baker_name)
bakes = 
  bakes |> rename(baker = baker)

anti_join(bakers, bakes, by = c("series", "baker"))

## merging
bakeoff_df = bakes |>
  full_join(results, bakes, by = c("series", "episode", "baker"))|> 
   full_join(bakers, by = c("series", "baker") |> 

head(bakeoff_df)

bakeoff_df=
  select(episode, series, baker, result, technical, results) |>

write.csv(bakeoff_df, "bakeoff_clean_set.csv", row.names = FALSE)|>
  
head(bakeoff_df)
```